[plugins]
shadow = "com.github.johnrengelman.shadow:8.1.0"

[versions]
mindustry = "v146"

[libraries]
anuken-arc = { module = "com.github.Anuken.Arc:arc-core", version.ref = "mindustry" }
anuken-mindustry = { module = "com.github.Anuken.Mindustry:core", version.ref = "mindustry" }
modlib = "com.github.Redstonneur1256.Mindustry-ModLib:Mod:1.4.5"
unifiedmetrics-api = "dev.cubxity.plugins:unifiedmetrics-api:0.3.6"
jsoup = "org.jsoup:jsoup:1.16.2"
